### ISSUE TITLE
NavBar fix for mobile view.

### ISSUE THREAD

**Issue by akramkazmi71** [niranjanhegde144/ISETechClub#11]
The toggle button does not work in mobile view after [hosting it](https://sce-tech-club.netlify.app/). Works fine locally.

-  Additionally, that also has some issues within:
   - collapseOnSelect does not work.

**Comment by Spoon-8285** [comment]
hey can i do this?

**Comment by rt1301** [comment]
I have added a PR for the fix

**Comment by FajarSJ** [comment]
Hi @akramkazmi71, can i contribute to this

**Comment by FajarSJ** [comment]
Hi @akramkazmi71, i have PR for this can you please kindly check it, i think my solution work much better for this situation rather than overriding the Component

**Comment by akramkazmi71** [comment]
Hi @FajarSJ, have looked at your PR but rt1301 made a PR first. I don't want to waste your time in this since someone else is already working on this issue.

I had some concern with your changes as well. But as someone else is already working on this we do not want to have multiple PRs on a single issue.

Hope you understand! :)
