### ISSUE TITLE
Add icon to the contributors page

### ISSUE THREAD

**Issue by niranjanhegde144** [niranjanhegde144/ISETechClub#14]
Contributors Page is rendered dynamically from the objects present in the contributors_details.json file present in the src directory. We can see that the contact key is an array of objects and each object has an icon key. We want to add a condition to the contributors.js file to render a particular font awesome icon based on the icon key.

**Comment by PhilippeBarre** [comment]
Hello,

I'm going to watch this

Best regards

**Comment by PhilippeBarre** [comment]
So I display the font awesome icon instead of the text "Profile" ?

**Comment by comrade-om** [comment]
Hi, I would be happy to contribute to this issue. Shall I start working on it @niranjanhegde144 ?

**Comment by niranjanhegde144** [comment]
Yes, PhilippeBarre. That's we want to replace the text profile with the appropriate font awesome icon.

**Comment by niranjanhegde144** [comment]
@comrade-om 

> So I display the font awesome icon instead of the text "Profile" ?

**Comment by niranjanhegde144** [comment]
comrade-om, Sorry but Phillippe Started working on this already. I don't want to waste your time on this as Philippe is already working on the issue. 
Someone else is already working on this we do not want to have multiple PRs on a single issue.
Hope you understand. :)

**Comment by comrade-om** [comment]
Yes got it, lemme know if any other issues arise :)
